### ISSUE TITLE
dpkg-deb: error: archive '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb' uses unknown compression for member 'control.tar.zst', giving up

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet-debian-meta#11]
```
# apt update && apt dist-upgrade
Hit:1 https://outerface.net/debian bullseye InRelease
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian-security bullseye-security InRelease 
Hit:4 https://deb.debian.org/debian bullseye-updates InRelease           
Hit:5 https://deb.debian.org/debian bullseye-proposed-updates InRelease  
Hit:6 https://deb.debian.org/debian bullseye-backports InRelease         
Hit:7 https://download.jitsi.org stable/ InRelease                       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  lua-basexx lua-cjson
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/26.8 kB of archives.
After this operation, 105 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
dpkg-deb: error: archive '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
dpkg-deb: error: archive '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: archive '/var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb
 /var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
zsh: exit 100   sudo -E apt dist-upgrade
```

```
% cat /etc/apt/sources.list.d/jitsi.list 
deb [signed-by=/usr/share/keyrings/jitsi-keyring.asc] https://download.jitsi.org stable/
% apt policy 
Package files:
 100 /var/lib/dpkg/status
     release a=now
 700 https://outerface.net/debian bullseye/main amd64 Packages
     release o=Outerface,a=stable,n=bullseye,l=outerface,c=main,b=amd64
     origin outerface.net
 500 https://download.jitsi.org stable/ Packages
     release o=jitsi.org,a=stable,n=stable,l=Jitsi Debian packages repository,c=
     origin download.jitsi.org
 100 https://deb.debian.org/debian bullseye-backports/non-free amd64 Packages
     release o=Debian Backports,a=bullseye-backports,n=bullseye-backports,l=Debian Backports,c=non-free,b=amd64
     origin deb.debian.org
 100 https://deb.debian.org/debian bullseye-backports/contrib amd64 Packages
     release o=Debian Backports,a=bullseye-backports,n=bullseye-backports,l=Debian Backports,c=contrib,b=amd64
     origin deb.debian.org
 100 https://deb.debian.org/debian bullseye-backports/main amd64 Packages
     release o=Debian Backports,a=bullseye-backports,n=bullseye-backports,l=Debian Backports,c=main,b=amd64
     origin deb.debian.org
 400 https://deb.debian.org/debian bullseye-proposed-updates/main amd64 Packages
     release v=11-updates,o=Debian,a=proposed-updates,n=bullseye-proposed-updates,l=Debian,c=main,b=amd64
     origin deb.debian.org
 500 https://deb.debian.org/debian bullseye-updates/main amd64 Packages
     release v=11-updates,o=Debian,a=stable-updates,n=bullseye-updates,l=Debian,c=main,b=amd64
     origin deb.debian.org
 500 https://deb.debian.org/debian-security bullseye-security/non-free amd64 Packages
     release v=11,o=Debian,a=stable-security,n=bullseye-security,l=Debian-Security,c=non-free,b=amd64
     origin deb.debian.org
 500 https://deb.debian.org/debian-security bullseye-security/main amd64 Packages
     release v=11,o=Debian,a=stable-security,n=bullseye-security,l=Debian-Security,c=main,b=amd64
     origin deb.debian.org
 500 https://deb.debian.org/debian bullseye/non-free amd64 Packages
     release v=11.5,o=Debian,a=stable,n=bullseye,l=Debian,c=non-free,b=amd64
     origin deb.debian.org
 500 https://deb.debian.org/debian bullseye/contrib amd64 Packages
     release v=11.5,o=Debian,a=stable,n=bullseye,l=Debian,c=contrib,b=amd64
     origin deb.debian.org
 500 https://deb.debian.org/debian bullseye/main amd64 Packages
     release v=11.5,o=Debian,a=stable,n=bullseye,l=Debian,c=main,b=amd64
     origin deb.debian.org
Pinned packages:
```

**Comment by damencho** [comment]
Thanks for the report. We are looking at it

**Comment by damencho** [comment]
This is fixed in stable. We will work on updating unstable with the correct packages later today.

**Comment by 532910** [comment]
I confirm that it works now.
